### ISSUE TITLE
Threading issue - threads hang iterating through HashMap keys

### ISSUE THREAD

**Issue by ucbjrl** [freechipsproject/treadle#92]
This appears to be similar to https://github.com/freechipsproject/firrtl/issues/1057. I haven't actually verified that this is the same cycle reported in that issue, but the symptoms suggest it.

I find 7 threads running Scala tests in approximately the same state:
```
"pool-12-thread-2-ScalaTest-running-GCDTester" #222 prio=5 os_prio=0 tid=0x00007f3f0d621800 nid=0x2a0c runnable [0x00007f3e387df000]
   java.lang.Thread.State: RUNNABLE
	at scala.runtime.BoxesRunTime.equalsNumObject(BoxesRunTime.java:140)
	at scala.runtime.BoxesRunTime.equals2(BoxesRunTime.java:129)
	at scala.runtime.BoxesRunTime.equals(BoxesRunTime.java:121)
	at scala.collection.mutable.HashTable.elemEquals(HashTable.scala:363)
	at scala.collection.mutable.HashTable.elemEquals$(HashTable.scala:363)
	at scala.collection.mutable.HashMap.elemEquals(HashMap.scala:40)
	at scala.collection.mutable.HashMap.notFound(HashMap.scala:104)
	at scala.collection.mutable.HashMap.findEntry(HashMap.scala:100)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:78)
	at treadle.utils.BitMasks$.getBitMasksBigs(BitUtils.scala:210)
	at treadle.executable.Symbol.<init>(Symbol.scala:23)
	at treadle.executable.Symbol$.apply(Symbol.scala:97)
```

The actual treadle code is:
```scala
def getBitMasksBigs(bitWidth: Int): BitMasksBigs = {
 alreadyCreatedBigs.getOrElseUpdate(bitWidth, BitMasksBigs(bitWidth))
}
```

As with the FIRRTL case, the `BitMask` caches:
```scala
  private val alreadyCreatedInts = new mutable.HashMap[Int, BitMasksInts]
  private val alreadyCreatedLongs = new mutable.HashMap[Int, BitMasksLongs]
  private val alreadyCreatedBigs = new mutable.HashMap[Int, BitMasksBigs]
```
should probably be part of a test-specific data structure, or at least, be protected against simultaneous access.

**Comment by chick** [comment]
These have been converted to `TrieMap` which seems to solve the multi-threaded issues.
For the record the following
```scala 
import org.scalatest.freespec.AnyFreeSpec
import org.scalatest.matchers.must._
import treadle.utils.BitMasks

import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global

class BitMaskTest extends AnyFreeSpec with Matchers {
  "Test multi-thread problems with bitmask" in {
    val rand = new util.Random
    val futures = Seq.fill(16) {
      Future {
        (1 until 1000).foreach { i =>
          BitMasks.getBitMasksBigs(i)
        }
      }
    }

    var done = false
    while( ! done ) {
      done = futures.forall(f => f.isCompleted)
    }

    for(i <- 1 until 1000) {
      BitMasks.alreadyCreatedBigs.contains(i) must be (true)
      BitMasks.alreadyCreatedBigs(i).allBitsMask must be (BigInt("1" * i, 2))
    }

  }
}
```
works fine with TrieMap but hangs if TrieMaps are changed to HashMaps. I am not implementing this test now because of difficulties in getting to internal structures for the test
